export const DATA_SEND_REQUEST = 'DATA_SEND_REQUEST';
export const DATA_SEND_SUCCESS = 'DATA_SEND_SUCCESS';
export const DATA_SEND_FAIL = 'DATA_SEND_FAIL';

export const GET_ALL_RESUME_REQUEST = 'GET_ALL_RESUME_REQUEST';
export const GET_ALL_RESUME_SUCCESS = 'GET_ALL_RESUME_SUCCESS';
export const GET_ALL_RESUME_FAIL = 'GET_ALL_RESUME_FAIL';

export const GET_RESUME_REQUEST = 'GET_RESUME_REQUEST';
export const GET_RESUME_SUCCESS = 'GET_RESUME_SUCCESS';
export const GET_RESUME_FAIL = 'GET_RESUME_FAIL';

export const UPDATE_RESUME_REQUEST = 'UPDATE_RESUME_REQUEST';
export const UPDATE_RESUME_SUCCESS = 'UPDATE_RESUME_SUCCESS';
export const UPDATE_RESUME_FAIL = 'UPDATE_RESUME_FAIL';

export const DEL_RESUME_REQUEST = 'DEL_RESUME_REQUEST';
export const DEL_RESUME_SUCCESS = 'DEL_RESUME_SUCCESS';
export const DEL_RESUME_FAIL = 'DEL_RESUME_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
